version: "3.3"
services:
  app:
    build: .
    restart: always
    environment:
      - VERSION=0.0.1
    image: boristax/graph-editor:v0.0.1
    ports:
      - "5555:5555"
    command: npm run start
    volumes: 
      - graph-db:/app/src/server/database
volumes:
  wardrobes-db:
      external: true